steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_URL}:${_IMAGE_TAG}', '.']

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URL}:${_IMAGE_TAG}']

  # Step 3: Scan the container image with Trivy and save the report
  - name: 'aquasec/trivy'
    args: ['image', '--format', 'json', '--output', '/workspace/trivy-report.json', '${_IMAGE_URL}:${_IMAGE_TAG}']
    id: 'trivy-scan'

  # Step 4: Upload the Trivy report to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/trivy-report.json', 'gs://pipeline-github/trivy-report.json']
    waitFor: ['trivy-scan']

  # Step 5: Print the Trivy results
  - name: 'ubuntu'
    entrypoint: 'cat'
    args: ['/workspace/trivy-report.json']

  # Step 6: Forward the logs to the SaaS platform using curl
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'curl --location --request POST "https://${_CSPM_URL}/api/v1/artifact/?tenant_id=${_TENANT_ID}&data_type=TR&save_to_s3=false" --header "Authorization: Bearer ${_CSPM_TOKEN}" --form "file=@/workspace/trivy-report.json"'
      ]

substitutions:
  _IMAGE_URL: 'gcr.io/gcp-cicd-test-425406/aditya-test'
  _IMAGE_TAG: 'latest'
  _CSPM_URL: 'cspm.demo.accuknox.com'
  _TENANT_ID: '167'

images:
  - 'gcr.io/gcp-cicd-test-425406/aditya-test:latest'

logsBucket: 'gs://pipeline-github'
timeout: '1200s'
#magic
