steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_URL}:${_IMAGE_TAG}', '.']

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URL}:${_IMAGE_TAG}']

  # Step 3: Download Trivy standalone binary and scan the container image
  - name: 'aquasec/trivy'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        trivy image --format json --output /workspace/trivy-report.json ${_IMAGE_URL}:${_IMAGE_TAG}
    id: 'trivy-scan'

  # Step 4: Print Trivy Results
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/trivy-report.json', 'gs://pipeline-github/trivy-report.json']
    waitFor: ['trivy-scan']

  # Step 5: Push report to CSPM panel
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl --location --request POST 'https://cspm.demo.accuknox.com/api/v1/artifact/?tenant_id=167&data_type=TR&save_to_s3=false' --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAzNjczOTYyLCJqdGkiOiIzOTUzYWM0YWE4YmQ0ZDdkYTRkZmQ0MDdjNGIyZTk4ZSIsImlzcyI6ImNzcG0uZGVtby5hY2N1a25veC5jb20ifQ.aFOxNA8_CF9PSj3XSN0Vsmq1h8LtseNQbMaCVP1EZhHMSkKMb814WujBQj3ViABXrpuPi4g935Ob1hRTf2XELENmN5WzWvthhy8VfFVrWfCqsjOWWs5HIPSF9s65neGkwEZghmU5kjt7C5WS1TIv8p2Z0Z0SZjSGVrCzNAy0Iwf2AUPinY2cWamVPQrdjTq2QOusJJX8g8IOdwLm9GnIjks78G_bAxmMfqs6i57Iw8yWvMXCzFkfpqkfaml8hM-YPm-4wz5toTXfyo8McNaNhfWKF6U-RyVpX1XtsudVugoY3vB9reJabr8mLPoGLLYo-6ad3OMdYBiQQ8Af6tu52Q' --form 'file=@"./trivy-report.json"'
    waitFor: ['trivy-scan']

substitutions:
  _IMAGE_URL: 'gcr.io/gcp-cicd-test-425406/aditya-test'
  _IMAGE_TAG: 'latest'

images:
  - 'gcr.io/gcp-cicd-test-425406/aditya-test:latest'

logsBucket: 'gs://pipeline-github'
timeout: '1200s'
